import {ENV_MODULES,environmentAccess,environmentPhase,environmentWeather,setEnvironment,resetEnvironment,ENV_RECORDS} from './environment.js';
const recordArt=id=>`<svg viewBox="0 0 16 16" width="20" height="20" fill="currentColor" aria-hidden="true">${({rain:'<path d="M3 2h8v2h3v5H1V4h2Z M3 11h2v4H3Z M9 11h2v4H9Z"/>',snow:'<path d="M7 0h2v5h2V3h2v2h-2v2h5v2h-5v2h2v2h-2v-2H9v5H7v-5H5v2H3v-2h2V9H0V7h5V5H3V3h2v2h2Z"/>',stars:'<path d="M7 1h2v4h2v2h4v2h-4v2H9v4H7v-4H5V9H1V7h4V5h2Z"/>',fireflies:'<path d="M2 3h3v3H2Z M10 1h2v2h-2Z M8 8h4v4H8Z M2 12h2v2H2Z"/>',meteor:'<path d="M1 12h3v3H1Z M4 9h3v3H4Z M7 6h3v3H7Z M10 3h3v3h-3Z M13 0h3v3h-3Z"/>'})[id]}</svg>`;
const recordMarkup=e=>e.seen.map(id=>{const at=e.observed?.[id],minutes=at?Math.floor(at.phase*1440):0;return `<li>${recordArt(id)}<span>${ENV_RECORDS[id]}</span><small>${at?`第 ${Math.floor(at.clock/480)+1} 日 · ${String(Math.floor(minutes/60)).padStart(2,'0')}:${String(minutes%60).padStart(2,'0')}`:'原有记录'}</small></li>`}).join('')||'<li>暂无记录</li>';
export function createObservatoryUI(api) {
 const changed=()=>{api.changed();refresh(document)};
 function markup(){const s=api.state(),e=s.environment;if(!environmentAccess(s))return '';
 return `<section class="observatory" aria-label="观象台"><header class="observation-reading"><div><small>世界时间</small><strong data-env-time></strong></div><div><small>天气</small><strong data-env-weather></strong></div></header>${e.access.pending?'<p>已有观象台使用资格，可以免费选择位置安放。</p><button class="primary" data-env-place>免费安放观象台</button>':''}<div class="observation-controls">${e.modules['env-sundial']?`<label>昼夜循环<input type="checkbox" data-env-cycle ${e.cycle?'checked':''}></label><label>固定时刻<input type="range" min="0" max="1439" step="1" data-env-time-input aria-label="世界时间" value="${Math.floor(e.phase*1440)}"></label>`:''}${e.modules['env-weather']?`<label>天气<select data-env-select>${[['clear','晴'],['cloudy','多云'],...(e.modules['env-rain']?[['rain','雨']]:[]),...(e.modules['env-snow']?[['snow','雪']]:[]),['auto','自动']].map(([id,name])=>`<option value="${id}" ${(e.auto?'auto':e.weather)===id?'selected':''}>${name}</option>`).join('')}</select></label>`:''}${e.modules['env-stars']?['stars','meteor',...(e.enabled.fireflies!==undefined?['fireflies']:[])].map(id=>`<label>${{stars:'星空',meteor:'流星',fireflies:'萤火'}[id]}<input type="checkbox" data-env-feature="${id}" ${e.enabled[id]?'checked':''}></label>`).join(''):''}${e.palettes.length?`<label>已收藏的天空<select data-env-palette><option value="">随昼夜变化</option>${e.palettes.map((id,j)=>`<option value="${id}" ${e.palette===id?'selected':''}>${['薄荷清晨','蜂蜜落日','末影星夜'][+id.slice(-1)]}</option>`).join('')}</select></label>`:''}</div><h4>购买与管理仪器</h4><div class="observation-instruments">${ENV_MODULES.map(i=>`<article data-env-item="${i.id}"><div><strong>${i.name}</strong><p>${i.desc}</p></div>${e.modules[i.id]?`<button data-env-toggle="${i.id}" aria-pressed="${e.enabled[i.id]!==false}">${e.enabled[i.id]!==false?'使用中 ✓':'已停用'}</button>`:`<button class="primary" data-env-buy="${i.id}">${i.cost} ◆</button>`}<small data-env-reason></small></article>`).join('')}</div><details><summary>观测记录 <span data-env-count>${e.seen.length}</span> / ${e.enabled.fireflies!==undefined?5:4}</summary><ul class="observation-records" data-env-records>${recordMarkup(e)}</ul></details><button class="quiet-button" data-env-reset>恢复晴天正午</button></section>`;
 }
 function bind(root){const on=(sel,fn)=>root.querySelectorAll(sel).forEach(b=>b.onclick=()=>fn(b));
 on('[data-env-buy]',b=>api.purchase(b.dataset.envBuy));on('[data-env-place]',()=>api.place());on('[data-env-toggle]',b=>{const e=api.state().environment,id=b.dataset.envToggle;setEnvironment(api.state(),{toggle:id,value:e.enabled[id]===false});b.setAttribute('aria-pressed',String(e.enabled[id]!==false));b.textContent=e.enabled[id]===false?'已停用':'使用中 ✓';changed()});
 on('[data-env-reset]',()=>{resetEnvironment(api.state());api.changed();api.rerender()});
 for(const x of root.querySelectorAll('[data-env-cycle]'))x.onchange=()=>{setEnvironment(api.state(),{cycle:x.checked});changed()};
 for(const x of root.querySelectorAll('[data-env-time-input]')){x.oninput=()=>{setEnvironment(api.state(),{phase:+x.value/1440});const c=root.querySelector('[data-env-cycle]');if(c)c.checked=false;refresh(root)};x.onchange=changed;}
 for(const x of root.querySelectorAll('[data-env-select]'))x.onchange=()=>{setEnvironment(api.state(),x.value==='auto'?{auto:true}:{weather:x.value});changed()};
 for(const x of root.querySelectorAll('[data-env-feature]'))x.onchange=()=>{setEnvironment(api.state(),{toggle:x.dataset.envFeature,value:x.checked});changed()};
 for(const x of root.querySelectorAll('[data-env-palette]'))x.onchange=()=>{setEnvironment(api.state(),{palette:x.value});changed()};
 refresh(root);
 }
 function refresh(root){const s=api.state(),e=s.environment,t=Math.floor(environmentPhase(s)*1440),time=String(Math.floor(t/60)).padStart(2,'0')+':'+String(t%60).padStart(2,'0');
 const set=(sel,text)=>root.querySelectorAll(sel).forEach(x=>{if(x.textContent!==text)x.textContent=text});
 set('[data-env-time]',time);set('[data-env-weather]',{clear:'晴',cloudy:'多云',rain:'雨',snow:'雪'}[environmentWeather(s)]);set('[data-env-count]',String(e.seen.length));root.querySelectorAll('[data-env-records]').forEach(x=>{const key=e.seen.join(',');if(x.dataset.records!==key){x.dataset.records=key;x.innerHTML=recordMarkup(e);}});
 root.querySelectorAll('[data-env-item]').forEach(row=>{const i=ENV_MODULES.find(x=>x.id===row.dataset.envItem);const missing=i.requires.filter(id=>!e.modules[id]);const reason=e.modules[i.id]?'':missing.length?'需要 '+missing.map(id=>ENV_MODULES.find(x=>x.id===id).name).join('、'):s.money<i.cost?`还差 ${Math.ceil(i.cost-s.money)} 绿宝石`:'';row.querySelector('[data-env-reason]').textContent=reason;});
 }
 return {markup,bind,refresh};
}
