// Dedicated purchase data. Fixed costs; no income-based repricing.
// Release values are finalized by the five-route integration calibration.
export const UPGRADE_CATALOG = [
  {
    id: "drill-steel",
    owner: "M9",
    ownerLevels: [1],
    name: "钢制钻头",
    basePrice: 4000,
    growth: 2,
    maxLevel: 1,
    dependencies: ["M9", "T3"],
    effects: {
      raw: 1.25,
    },
    energy: {
      work: 1.1,
    },
    model: "钢灰色交错钻齿，保留旋转轴",
  },
  {
    id: "drill-diamond",
    owner: "M9",
    ownerLevels: [3],
    name: "钻石钻头",
    basePrice: 32000,
    growth: 2,
    maxLevel: 1,
    dependencies: ["M9", "drill-steel", "T5"],
    effects: {
      raw: 1.45,
    },
    energy: {
      work: 1.15,
    },
    model: "青蓝色硬质钻齿和加厚轴套",
  },
  {
    id: "drill-netherite",
    owner: "M9",
    ownerLevels: [5],
    name: "下界合金钻头",
    basePrice: 14000000,
    growth: 2,
    maxLevel: 1,
    dependencies: ["M9", "drill-diamond", "N11"],
    effects: {
      raw: 1.8,
    },
    energy: {
      work: 1.2,
    },
    model: "深色合金刀头与铜色压环",
  },
  {
    id: "drill-twin",
    owner: "M9",
    ownerLevels: [3],
    name: "双轴钻架",
    basePrice: 18000,
    growth: 2,
    maxLevel: 1,
    dependencies: ["M9", "drill-steel"],
    effects: {
      raw: 1.65,
    },
    energy: {
      work: 1.7,
    },
    model: "两个独立往复钻轴、横向支架",
  },
  {
    id: "drill-cooling",
    owner: "M9",
    ownerLevels: [2],
    name: "冷却与传动",
    basePrice: 12000,
    growth: 2,
    maxLevel: 1,
    dependencies: ["M9", "M7"],
    effects: {
      raw: 1.15,
    },
    energy: {
      work: 0.78,
    },
    model: "侧面散热片、蓝色水箱与传动齿轮",
  },
  {
    id: "drill-buffer",
    owner: "M9",
    ownerLevels: [1, 2, 3],
    name: "缓冲料斗",
    basePrice: 6000,
    growth: 2.1,
    maxLevel: 3,
    dependencies: ["M9", "M4"],
    effects: {
      buffer: 2,
    },
    energy: {
      work: 1,
    },
    model: "出料口下方堆叠漏斗及可见料位",
  },
  {
    id: "drill-outlet",
    owner: "M9",
    ownerLevels: [2],
    name: "自动出料臂",
    basePrice: 15000,
    growth: 2,
    maxLevel: 1,
    dependencies: ["M9", "M8"],
    effects: {
      outlet: 3.4,
    },
    energy: {
      addWork: 1,
    },
    model: "仅在真实出货时伸缩的侧面推料臂",
  },
  {
    id: "furnace-core",
    owner: "M2",
    ownerLevels: [1, 2, 3],
    name: "高温炉芯",
    basePrice: 2200,
    growth: 2.5,
    maxLevel: 3,
    dependencies: ["M2", "T3"],
    effects: {
      localValue: 1.12,
      process: 1.45,
    },
    energy: {
      work: 1.2,
    },
    model: "加厚炉芯与分层橙色内火",
  },
  {
    id: "furnace-lining",
    owner: "M2",
    ownerLevels: [1],
    name: "隔热内衬",
    basePrice: 3600,
    growth: 2,
    maxLevel: 1,
    dependencies: ["M2"],
    effects: {
      process: 1.1,
    },
    energy: {
      work: 0.7,
    },
    model: "深色耐火砖围边",
  },
  {
    id: "furnace-blower",
    owner: "M2",
    ownerLevels: [2],
    name: "鼓风组件",
    basePrice: 6500,
    growth: 2,
    maxLevel: 1,
    dependencies: ["M2", "M7"],
    effects: {
      process: 1.6,
    },
    energy: {
      addWork: 3,
    },
    model: "侧置方形风箱与转动风叶",
  },
  {
    id: "furnace-feed",
    owner: "M2",
    ownerLevels: [2],
    name: "自动进料",
    basePrice: 7800,
    growth: 2,
    maxLevel: 1,
    dependencies: ["M2", "M8"],
    effects: {
      inlet: 3,
    },
    energy: {
      addWork: 1,
    },
    model: "进料架及随输入流移动的矿料",
  },
  {
    id: "wind-blades",
    owner: "M7",
    ownerLevels: [1, 2, 3],
    name: "宽面叶片",
    basePrice: 6500,
    growth: 2.4,
    maxLevel: 3,
    dependencies: ["M7"],
    effects: {
      generation: 1.35,
    },
    energy: {},
    model: "叶片增加木板条而非整体放大",
  },
  {
    id: "wind-gears",
    owner: "M7",
    ownerLevels: [2],
    name: "齿轮箱",
    basePrice: 10000,
    growth: 2,
    maxLevel: 1,
    dependencies: ["M7", "M10"],
    effects: {
      generation: 1.3,
    },
    energy: {},
    model: "机座外露双齿轮与转轴",
  },
  {
    id: "wind-coils",
    owner: "M7",
    ownerLevels: [3],
    name: "发电线圈",
    basePrice: 18000,
    growth: 2,
    maxLevel: 1,
    dependencies: ["M7", "M11"],
    effects: {
      generation: 1.65,
    },
    energy: {},
    model: "铜线圈与红石指示块",
  },
  {
    id: "torch-bank",
    owner: "M6",
    ownerLevels: [1, 2, 3],
    name: "火把组",
    basePrice: 500,
    growth: 2.5,
    maxLevel: 3,
    dependencies: ["M6"],
    effects: {
      generation: 1.3,
    },
    energy: {},
    model: "台座逐步增加小红石火把",
  },
  {
    id: "torch-core",
    owner: "M6",
    ownerLevels: [1],
    name: "稳定核心",
    basePrice: 1200,
    growth: 2,
    maxLevel: 1,
    dependencies: ["M6"],
    effects: {
      generation: 1.2,
      storage: 120,
    },
    energy: {},
    model: "方形稳定器与内层红光",
  },
  {
    id: "torch-module",
    owner: "M6",
    ownerLevels: [2],
    name: "红石供能模块",
    basePrice: 3600,
    growth: 2,
    maxLevel: 1,
    dependencies: ["M6", "M10"],
    effects: {
      generation: 1.25,
    },
    energy: {},
    model: "堆叠式红石模块及接线端子",
  },
  {
    id: "store-shelves",
    owner: "M4",
    ownerLevels: [1, 2, 3],
    name: "分层货架",
    basePrice: 1200,
    growth: 2.4,
    maxLevel: 3,
    dependencies: ["M4"],
    effects: {
      buffer: 1.6,
    },
    energy: {},
    model: "增加可见货架和相应箱堆",
  },
  {
    id: "store-compress",
    owner: "M4",
    ownerLevels: [2],
    name: "压缩容器",
    basePrice: 12000,
    growth: 2,
    maxLevel: 1,
    dependencies: ["M4", "M3"],
    effects: {
      buffer: 2.2,
    },
    energy: {
      addWork: 0.5,
    },
    model: "金属包角及压缩箱盖",
  },
  {
    id: "store-sort",
    owner: "M4",
    ownerLevels: [3],
    name: "分类出口",
    basePrice: 14000,
    growth: 2,
    maxLevel: 1,
    dependencies: ["M4", "M12"],
    effects: {
      outlet: 1.5,
    },
    energy: {
      addWork: 0.8,
    },
    model: "三类颜色出口，出货时指示亮起",
  },
  {
    id: "rail-wagons",
    owner: "M16",
    ownerLevels: [1, 2, 3],
    name: "扩容车厢",
    basePrice: 8000,
    growth: 2.5,
    maxLevel: 3,
    dependencies: ["M16"],
    effects: {
      cargo: 1.5,
    },
    energy: {
      work: 1.1,
    },
    model: "矿车增加实际车厢及载货箱",
  },
  {
    id: "rail-dispatch",
    owner: "M16",
    ownerLevels: [2, 3],
    name: "加密车次",
    basePrice: 16000,
    growth: 2.8,
    maxLevel: 2,
    dependencies: ["M16", "M10"],
    effects: {
      interval: 0.75,
    },
    energy: {
      work: 1.25,
    },
    model: "发车灯和第二组停车位",
  },
  {
    id: "rail-loader",
    owner: "M16",
    ownerLevels: [3],
    name: "快速装卸机构",
    basePrice: 26000,
    growth: 2,
    maxLevel: 1,
    dependencies: ["M16", "M17"],
    effects: {
      loading: 1.6,
    },
    energy: {
      addWork: 1.5,
    },
    model: "装卸臂按真正的停靠/载货状态工作",
  },
  {
    id: "farm-irrigation",
    owner: "V4",
    ownerLevels: [1],
    name: "田间灌渠",
    basePrice: 900,
    growth: 2,
    maxLevel: 1,
    dependencies: ["V4", "V6"],
    effects: {
      growthPeriod: 0.85,
    },
    energy: {},
    model: "沟渠和分水闸，成熟状态保留",
  },
  {
    id: "farm-beds",
    owner: "V4",
    ownerLevels: [1, 2, 3],
    name: "精耕苗床",
    basePrice: 1600,
    growth: 2.2,
    maxLevel: 3,
    dependencies: ["V4", "V5"],
    effects: {
      localValue: 1.12,
      harvest: 1.3,
    },
    energy: {},
    model: "整齐苗床与种子托盘",
  },
  {
    id: "farm-cart",
    owner: "V4",
    ownerLevels: [2],
    name: "收获小车",
    basePrice: 2600,
    growth: 2,
    maxLevel: 1,
    dependencies: ["V4", "M4"],
    effects: {
      jobWork: 1.3,
      buffer: 1.5,
    },
    energy: {},
    model: "田边手推车，跟随真实收获/交接动作",
  },
  {
    id: "pen-feed",
    owner: "V7",
    ownerLevels: [1, 2],
    name: "分栏饲槽",
    basePrice: 2400,
    growth: 2.5,
    maxLevel: 2,
    dependencies: ["V7", "V6"],
    effects: {
      localValue: 1.12,
      harvest: 1.3,
    },
    energy: {},
    model: "牛羊分区饲槽及料箱",
  },
  {
    id: "pen-tools",
    owner: "V7",
    ownerLevels: [2],
    name: "牧养工具台",
    basePrice: 4000,
    growth: 2,
    maxLevel: 1,
    dependencies: ["V7", "V11"],
    effects: {
      jobWork: 1.4,
    },
    energy: {},
    model: "剪毛台、清理刷和职业工具",
  },
  {
    id: "market-pack",
    owner: "V3",
    ownerLevels: [1, 2, 3],
    name: "打包柜台",
    basePrice: 3800,
    growth: 2.6,
    maxLevel: 3,
    dependencies: ["V3", "M4"],
    effects: {
      trade: 1.4,
    },
    energy: {},
    model: "纸箱、称台与分拣槽",
  },
  {
    id: "market-orders",
    owner: "V3",
    ownerLevels: [1],
    name: "农牧订单簿",
    basePrice: 8000,
    growth: 2,
    maxLevel: 1,
    dependencies: ["V3", "V17"],
    effects: {
      cropOrders: true,
    },
    energy: {},
    model: "柜台上的订单簿与交付箱",
  },
  {
    id: "library-tools",
    owner: "V11",
    name: "职业工具架",
    basePrice: 6500,
    growth: 2,
    maxLevel: 1,
    dependencies: ["V11", "V12"],
    effects: {
      jobWork: 1.2,
    },
    energy: {},
    model: "六种岗位工具，居民使用对应工具",
  },
  {
    id: "blaze-reservoir",
    owner: "N3",
    stageRequires: [[], ["N4"], ["N11"]],
    name: "烈焰蓄热环",
    basePrice: 360000,
    growth: 2.2,
    maxLevel: 3,
    dependencies: ["N3"],
    effects: {
      heat: 1.4,
    },
    energy: {},
    model: "烈焰棒环绕方形蓄热器",
  },
  {
    id: "blaze-feed",
    owner: "N3",
    name: "热能导管",
    basePrice: 800000,
    growth: 2,
    maxLevel: 1,
    dependencies: ["N3", "N4"],
    effects: {
      heatDelivery: 1.35,
    },
    energy: {},
    model: "连接烈焰人与热能设施的短管与热脉冲",
  },
  {
    id: "blaze-exchanger",
    owner: "N4",
    ownerLevels: [1],
    name: "余热发电",
    basePrice: 1600000,
    growth: 2,
    maxLevel: 1,
    dependencies: ["N4"],
    effects: {
      heatRecovery: 1.5,
    },
    energy: {},
    model: "铜色换热片，仅在炉体实际加工时回收热量",
  },
  {
    id: "blaze-chamber",
    owner: "N4",
    ownerLevels: [1, 2, 3],
    name: "密闭炉膛",
    basePrice: 2500000,
    growth: 2.4,
    maxLevel: 3,
    dependencies: ["N4", "N3"],
    effects: {
      process: 1.55,
    },
    energy: {
      work: 1.15,
    },
    model: "耐火砖炉膛与出料口",
  },
  {
    id: "piglin-crates",
    owner: "N2",
    ownerLevels: [2],
    name: "加固货箱",
    basePrice: 600000,
    growth: 2,
    maxLevel: 1,
    dependencies: ["N2", "N12"],
    effects: {
      trade: 1.35,
    },
    energy: {},
    model: "镶金加固箱，处理已交付的货物",
  },
  {
    id: "piglin-contract",
    owner: "N2",
    ownerLevels: [1],
    name: "异界订单契约",
    basePrice: 700000,
    growth: 2,
    maxLevel: 1,
    dependencies: ["N2"],
    effects: {
      piglinOrders: true,
    },
    energy: {},
    model: "营地契约台与收货秤",
  },
  {
    id: "magma-press",
    owner: "N5",
    name: "热压工作台",
    basePrice: 1400000,
    growth: 2,
    maxLevel: 1,
    dependencies: ["N5"],
    effects: {
      batch: 1.5,
    },
    energy: {
      work: 1.25,
    },
    model: "上下方形压板，按批次蓄料/压制/出料",
  },
  {
    id: "ghast-harness",
    owner: "N6",
    name: "空运货架",
    basePrice: 2800000,
    growth: 2,
    maxLevel: 1,
    dependencies: ["N6"],
    effects: {
      cargo: 1.6,
    },
    energy: {},
    model: "恶魂下方悬挂实际载货箱",
  },
  {
    id: "nether-customs",
    owner: "N12",
    name: "货运分流台",
    basePrice: 5000000,
    growth: 2,
    maxLevel: 1,
    dependencies: ["N12", "M12"],
    effects: {
      transfer: 1.5,
    },
    energy: {
      addWork: 2,
    },
    model: "双向装卸口与来源颜色标记",
  },
  {
    id: "forge-anvil",
    owner: "N11",
    name: "精密合金模具",
    basePrice: 12000000,
    growth: 2,
    maxLevel: 1,
    dependencies: ["N11", "N4"],
    effects: {
      goodsValue: 1.2,
    },
    energy: {
      addWork: 2,
    },
    model: "合金模具和机械锤，只加工已输入材料",
  },
  {
    id: "end-anchor",
    owner: "E3",
    name: "瞬移锚点",
    basePrice: 50000000,
    growth: 2,
    maxLevel: 1,
    dependencies: ["E3"],
    effects: {
      interval: 0.8,
    },
    energy: {},
    model: "端点方块和离散瞬移粒子",
  },
  {
    id: "end-relay",
    owner: "E3",
    stageRequires: [[], ["E7"]],
    name: "接力背篓",
    basePrice: 80000000,
    growth: 2.4,
    maxLevel: 2,
    dependencies: ["E3", "E6"],
    effects: {
      cargo: 1.5,
    },
    energy: {},
    model: "末影人背篓，只有载货时呈现货箱",
  },
  {
    id: "shulker-coil",
    owner: "E5",
    name: "悬浮稳定环",
    basePrice: 75000000,
    growth: 2,
    maxLevel: 1,
    dependencies: ["E5"],
    effects: {
      loading: 1.4,
    },
    energy: {
      work: 1.15,
    },
    model: "紫色稳定环，货箱按队列悬浮",
  },
  {
    id: "shulker-dock",
    owner: "E5",
    name: "双臂装卸台",
    basePrice: 120000000,
    growth: 2,
    maxLevel: 1,
    dependencies: ["E5", "M17"],
    effects: {
      loading: 1.55,
    },
    energy: {
      addWork: 2,
    },
    model: "两侧升降臂和独立箱位",
  },
  {
    id: "shulker-cells",
    owner: "E6",
    ownerLevels: [1, 2],
    name: "内部分隔",
    basePrice: 160000000,
    growth: 2.5,
    maxLevel: 2,
    dependencies: ["E6"],
    effects: {
      cargo: 1.4,
      buffer: 1.3,
    },
    energy: {},
    model: "潜影盒分格与更密的载货布局",
  },
  {
    id: "ender-routing",
    owner: "E7",
    name: "转运缓存",
    basePrice: 300000000,
    growth: 2,
    maxLevel: 1,
    dependencies: ["E7", "M12"],
    effects: {
      transfer: 1.5,
    },
    energy: {
      addWork: 2,
    },
    model: "三维度端口，不取消铁路末端配送",
  },
  {
    id: "chorus-roots",
    owner: "E4",
    ownerLevels: [2],
    name: "连生根系",
    basePrice: 90000000,
    growth: 2,
    maxLevel: 1,
    dependencies: ["E4"],
    effects: {
      harvest: 1.5,
      chain: 3,
    },
    energy: {},
    model: "相连紫颂枝，每波采收逐株亮起",
  },
  {
    id: "brew-cooling",
    owner: "E10",
    name: "龙息冷凝器",
    basePrice: 2000000000,
    growth: 2,
    maxLevel: 1,
    dependencies: ["E10", "N11"],
    effects: {
      brewPeriod: 0.8,
      boostDuration: 1.2,
    },
    energy: {
      addWork: 3,
    },
    model: "冷凝盘管与气泡收集瓶",
  },
  {
    id: "terrarium-climate",
    owner: "E11",
    ownerLevels: [2],
    name: "维度温室",
    basePrice: 4000000000,
    growth: 2,
    maxLevel: 1,
    dependencies: ["E11", "E10"],
    effects: {
      raw: 1.5,
      brewSynergy: 1.2,
    },
    energy: {
      addWork: 4,
    },
    model: "玻璃方罩中的异界小树与气候粒子",
  },
  {
    id: "dragon-rig",
    owner: "E9",
    name: "龙背货舱",
    basePrice: 1800000000,
    growth: 2,
    maxLevel: 1,
    dependencies: ["E9", "E6"],
    effects: {
      cargo: 1.6,
    },
    energy: {},
    model: "背部货舱、归航时实际卸下大宗货物",
  },
  {
    id: "dragon-route",
    owner: "E9",
    name: "巡游航标",
    basePrice: 2400000000,
    growth: 2,
    maxLevel: 1,
    dependencies: ["E9", "E7"],
    effects: {
      interval: 0.75,
    },
    energy: {
      addWork: 1,
    },
    model: "三个维度的航标，起飞/运输/抵达各有状态",
  },
];
export const UPGRADE_BY_ID = Object.fromEntries(
  UPGRADE_CATALOG.map((row) => [row.id, row]),
);
