// Describe the installed part and its actual job together. Values belong in the
// comparison below, where other installed parts and throughput limits are known.
export const UPGRADE_COPY = {
  'drill-steel': '换上钢制钻齿，多采一些矿料，也会多用一点电。',
  'drill-diamond': '换上钻石钻齿，提高开采能力。出料口也得来得及把矿料送走。',
  'drill-netherite': '换上合金刀头，提高深层开采能力。如果出料口已经堵住，先升级出料。',
  'drill-twin': '增加一组钻轴，同时开采更多矿料，工作耗电也明显增加。',
  'drill-cooling': '加装水箱和散热片，少用一些电，开采能力也小幅提升。',
  'drill-buffer': '在出料口下方加装料斗，让主世界能暂存更多原料。',
  'drill-outlet': '加装推料臂，让出料口每秒送走更多矿料。',
  'furnace-core': '加厚炉芯，多加工一些矿料，成品也更值钱。',
  'furnace-lining': '砌上耐火砖内衬，减少工作耗电，加工也稍快一些。',
  'furnace-blower': '在炉侧加装风箱，提高加工能力；需要额外供电。',
  'furnace-feed': '加装进料架，每秒能往炉内送进更多矿料。',
  'wind-blades': '加宽叶片，每秒能发出更多电。',
  'wind-gears': '在机座装上齿轮箱，提高风车的发电量。',
  'wind-coils': '增加铜线圈，进一步提高发电量。',
  'torch-bank': '在底座增添红石火把，增加持续供电。',
  'torch-core': '装入稳定核心，增加发电量，也让电网多存一些电。',
  'torch-module': '堆叠新的供能模块，增加持续供电。',
  'store-shelves': '增加分层货架，让各维度的仓储都能多放一些货。',
  'store-compress': '加装压缩箱盖，让各个世界的仓库装得更多。有货时需要额外供电。',
  'store-sort': '增设分类出口，提高仓库的出货能力。',
  'rail-wagons': '增加载货车厢，让铁路能运走更多货物。',
  'rail-dispatch': '增设发车灯和停车位，让矿车更密集地发车。',
  'rail-loader': '加装装卸臂，让矿车更快装好货、卸完货。',
  'farm-irrigation': '在田间铺设水渠，让作物早一些成熟。',
  'farm-beds': '整理苗床，作物收得更多，也能卖出更好的价钱。',
  'farm-cart': '在田边添置小车，让农夫工作更快，也能暂存更多待运农产品。',
  'pen-feed': '增添分栏饲槽，羊毛产量和售价一起提高。',
  'pen-tools': '添置剪毛工具台，让牧民更快完成工作。',
  'market-pack': '增加称台和打包柜台，让送来的货更快卖出去。',
  'market-orders': '摆上订单簿，开始接取额外的农牧订单。',
  'library-tools': '备齐各岗位的工具，让全村已安排工作的村民做事更快。',
  'blaze-reservoir': '增添蓄热器，存下更多烈焰热能，留给下界工业使用。',
  'blaze-feed': '接上热能导管，让烈焰人更快补充热能。',
  'blaze-exchanger': '加装换热片，在炉体加工时回收更多热量用于发电。',
  'blaze-chamber': '砌起密闭炉膛，提高下界加工能力，也会多耗一些电。',
  'piglin-crates': '换上加固货箱，让猪灵交易营更快处理送来的货。',
  'piglin-contract': '设立契约台，开始接取额外的猪灵订单。',
  'magma-press': '加装上下压板，让岩浆怪每批能压制更多原料。',
  'ghast-harness': '为恶魂挂上货架，每趟空运能带走更多货物。',
  'nether-customs': '增设双向装卸口，提高主世界与下界之间的转运能力。',
  'forge-anvil': '装入精密模具，让锻台加工出的合金成品更值钱。',
  'end-anchor': '布置瞬移锚点，缩短末影人两次运输的间隔。',
  'end-relay': '为末影人添置背篓，每趟能搬走更多货物。',
  'shulker-coil': '加装悬浮稳定环，让潜影贝更快装卸货物。',
  'shulker-dock': '增设两侧装卸臂，进一步加快货物交接。',
  'shulker-cells': '在潜影盒内增加分格，同时扩大仓储和运输容量。',
  'ender-routing': '增设跨维度转运端口，加快货物转运。',
  'chorus-roots': '让紫颂枝连生，增加收成，并能连续采收三批。',
  'brew-cooling': '加装冷凝管，更快酿好龙息，强化效果也能持续更久。',
  'terrarium-climate': '搭起玻璃温室，提高盆栽产出；龙息强化期间收成更多。',
  'dragon-rig': '为末影龙加装背部货舱，每趟巡游能运回更多货物。',
  'dragon-route': '布置巡游航标，让末影龙更快开始下一趟运输。',
};

export const UPGRADE_PURPOSE = {
 'drill-steel':'加快采矿', 'drill-diamond':'开采更多矿料', 'drill-netherite':'强化深层开采',
 'drill-twin':'增加开采轴', 'drill-cooling':'采得更快，更省电', 'drill-buffer':'原料容量翻倍', 'drill-outlet':'放宽出料限制',
 'furnace-core':'加快矿料加工', 'furnace-lining':'省电，兼顾加工', 'furnace-blower':'增强加工能力', 'furnace-feed':'放宽进料限制',
 'wind-blades':'增加发电量', 'wind-gears':'提高发电效率', 'wind-coils':'增强持续供电',
 'torch-bank':'增加持续供电', 'torch-core':'发电、储电一起提升', 'torch-module':'增加持续供电',
 'store-shelves':'多存一些货物', 'store-compress':'扩大仓储容量', 'store-sort':'加快仓库出货',
 'rail-wagons':'运走更多货物', 'rail-dispatch':'增加发车频率', 'rail-loader':'加快装卸交接',
 'farm-irrigation':'让作物早些成熟', 'farm-beds':'每次收成更多', 'farm-cart':'加快农务，多存收成',
 'pen-feed':'每次多收些羊毛', 'pen-tools':'让牧民工作更快',
 'market-pack':'更快卖出货物', 'market-orders':'接取额外农牧订单', 'library-tools':'全村岗位效率提升',
 'blaze-reservoir':'储备更多热能', 'blaze-feed':'更快补充热能', 'blaze-exchanger':'加工时多发一些电', 'blaze-chamber':'提高下界加工能力',
 'piglin-crates':'更快处理交易货物', 'piglin-contract':'接取额外猪灵订单', 'magma-press':'每批压制更多原料',
 'ghast-harness':'每趟多带些货物', 'nether-customs':'加快下界转运', 'forge-anvil':'让合金成品更值钱',
 'end-anchor':'缩短运输间隔', 'end-relay':'每趟多搬些货物', 'shulker-coil':'加快悬浮装卸', 'shulker-dock':'加快货物交接',
 'shulker-cells':'多装货，多存货', 'ender-routing':'加快跨维度转运', 'chorus-roots':'增加收成，连收三批',
 'brew-cooling':'酿造更快，强化更久', 'terrarium-climate':'提高异界种植产出',
 'dragon-rig':'每趟运回更多货物', 'dragon-route':'缩短龙的运输间隔',
};
